### PR TITLE
Latest API Kit -Updated

### PR DESCRIPTION
**Pull request by SankariSM**

### CODE REVIEW

**Review by FabienSerny — COMMENTED** [review]
Using class name for construct method is not allowed on some PHP Version.
Accepting this would cause trouble to many users (that's why I changed it some time ago)

**Comment by SankariSM** [comment]
> Using class name for construct method is not allowed on some PHP Version. Accepting this would cause trouble to many users (that's why I changed it some time ago)

Actually I have downloaded the latest KIT API(Which was already created by someone) just i integrated into the module. So i didn't make change. So please let me know need to change?

**Comment by FabienSerny** [comment]
In my opinion, we should not merge this part of the API Kit (I merged the other parts) to avoid support request.

**Comment by FabienSerny** [comment]
I deny this PR to avoid support

**Pull request closed without merging**
